dataset: mot

train_split: mot17_train_coco
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: data/MOT17
mot_path_val: data/MOT17

resume: /home/seu2/a_back/wzhdata/724/RadarTracker/models/custom_dataset_deformable/checkpoint_epoch_1530.pth

epochs: 50
lr_drop: 10